services:
  gpio_control:
    image: nkoeppe/gpio_control:latest
    build:
      context: ./gpio_control
      dockerfile: Dockerfile
    container_name: gpio_control
    privileged: true
    environment:
      - CONTROL_CONFIG=/config/control_config.json
      - PYTHONPATH=/app
    volumes:
      - ./gpio_control:/app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - 5000:5000
    restart: always

  gpio_deamon:
    image: zinen2/alpine-pigpiod:latest
    container_name: gpio_deamon
    privileged: true
    ports:
      - 8888:8888
    restart: always

  serial_proxy:
    build: ./serial_proxy
    volumes:
      - ./serial_proxy:/app
    devices:
      - "/dev/ttyACM0:/dev/ttyUSB0"
    restart: always

  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    hostname: motioneye
    ports:
      - "8082:8081" 
      - "8765:8765"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    devices:
      - "/dev/video0:/dev/video0" 
    restart: always


  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  grafana-storage:
